org.codehaus.groovy.eclipse.ui.autoEditorClosingEnabled=true
groovy.editor.highlight.default.enabled=true
groovy.editor.highlight.groovykeywords.enabled=true
groovy.editor.highlight.javakeywords.enabled=true
groovy.editor.highlight.javatypes.enabled=true
groovy.editor.highlight.multilinecomments.enabled=true
groovy.editor.highlight.numbers.enabled=true
groovy.editor.highlight.strings.enabled=true
groovy.editor.highlight.annotation.enabled=true
groovy.editor.highlight.bracket.enabled=true
groovy.editor.highlight.operator.enabled=true 